{{ if .Values.hub.persistent_home }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "nublado.fullname" . }}-hub-physpvc
  annotations:
    pv.beta.kubernetes.io/gid: "{{ .Values.hub.gid }}"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi
{{ end }}
