{{ if .Values.vault_secrets.enabled }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "nublado.fullname" . }}-hub
  labels:
    app: {{ template "nublado.fullname" . }}
{{ include "nublado.labels" . | indent 4 }}
spec:
  path: {{ .Values.vault_secrets.path }}
  type: Opaque
{{ end }}
