apiVersion: v1
kind: Service
metadata:
  name: {{ template "nublado.fullname" . }}-wf-api
  labels:
    name: {{ template "nublado.fullname" . }}-wf-api
spec:
  type: LoadBalancer
  ports:
  - name: api
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: {{ template "nublado.fullname" . }}-wf-api
