apiVersion: v1
kind: Service
metadata:
  name: {{ include "firefly.fullname" . }}-redis
  labels:
{{ include "firefly.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "firefly.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP 
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
