apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firefly.fullname" . }}-redis
  labels:
{{ include "firefly.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "firefly.name" . }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "firefly.name" . }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: redis-srv
        image: redis:5
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "firefly.fullname" . }}-secret
              key: ADMIN_PASSWORD
        command: ["redis-server"]
        args: ["--requirepass", "$(REDIS_PASSWORD)"]
