apiVersion: v1
kind: Service
metadata:
  name: {{ include "firefly.fullname" . }}
  labels:
{{ include "firefly.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "firefly.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
