{{ if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cadc-tap.fullname" . }}-secrets
  labels:
    app: {{ template "cadc-tap.fullname" . }}
{{ include "cadc-tap.labels" . | indent 4 }}
type: Opaque
data:
  "google_creds.json": {{ .Values.secrets.google_creds | b64enc }}
  "slack_webhook_url": {{ .Values.secrets.slack_webhook_url | b64enc }}
{{ end }}
