kind: Service
apiVersion: v1
metadata:
  name: {{ template "cadc-tap.fullname" . }}-tap-schema-db
  labels:
    app: {{ template "cadc-tap.fullname" . }}-tap-schema-db
{{ include "cadc-tap.labels" . | indent 4 }}
spec:
  selector:
    app: {{ template "cadc-tap.fullname" . }}-tap-schema-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
