{{ if .Values.vault_secrets.enabled }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ template "cadc-tap.fullname" . }}-secrets
  labels:
    app: {{ template "cadc-tap.fullname" . }}
{{ include "cadc-tap.labels" . | indent 4 }}
spec:
  path: {{ .Values.vault_secrets.path }}
  type: Opaque
{{ end }}
