kind: Service
apiVersion: v1
metadata:
  name: {{ template "landing-page.fullname" . }}
  labels:
    app: {{ template "landing-page.fullname" . }}
    chart: {{ template "landing-page.chart" . }}
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: {{ template "landing-page.fullname" . }}
